### ISSUE TITLE
This repository has the wrong files and wrong commit history

### ISSUE THREAD

**Issue by teohhanhui** [flathub/com.github.qarmin.szyszka#1]
From https://github.com/flathub/flathub/pull/2438#issuecomment-896263264

**Comment by qarmin** [comment]
Is this a problem?
Looks that app was properly submitted to flathub - https://flathub.org/apps/details/com.github.qarmin.szyszka

**Comment by teohhanhui** [comment]
It confuses the user who ends up landing on this repository. The README etc. would all point them in the wrong direction :)

**Comment by teohhanhui** [comment]
And if you look at https://github.com/flathub/com.github.qarmin.szyszka/actions you'll see further problems due to the presence of the wrong `.github` folder and its workflows...

**Comment by qarmin** [comment]
Now should be fine.
With previous app I forked proper branch but looks that I forgot how to do this
